version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eapserverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lhf3r1josozw"
s3_prefix = "eapserverless"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

