Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        TABLE_NAME: inneedEap
        AWS_REGION_DYNAMODB: us-west-2
        


Resources:
  EAPCompanyCRUDFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-company-crud
      CodeUri: ./company-crud
      Handler: app.crud_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        CompanyPOST:
          Type: Api
          Properties:
            Path: /company
            Method: POST
            RestApiId:
              Ref: EAPApi
        CompanyGETPUT:
          Type: Api
          Properties:
            Path: /company/{company_id}
            Method: ANY
            RestApiId:
              Ref: EAPApi
              
  EAPUserCRUDFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-user-crud
      CodeUri: ./user-crud
      Handler: app.crud_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        UserPOST:
          Type: Api
          Properties:
            Path: /user/{company_id}
            Method: POST
            RestApiId:
              Ref: EAPApi
        UserGETPUT:
          Type: Api
          Properties:
            Path: /user/{company_id}/{user_id}
            Method: ANY
            RestApiId:
              Ref: EAPApi
              
  EAPGetCompanyPostsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-get-posts-by-company
      CodeUri: ./company-posts
      Handler: app.get_company_posts
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        UserGet:
          Type: Api
          Properties:
            Path: /postsByCompany
            Method: GET
            RestApiId:
              Ref: EAPApi
              
  EAPGetAdminPostsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-get-posts-by-admin
      CodeUri: ./admin-posts
      Handler: app.get_admin_posts
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        UserGet:
          Type: Api
          Properties:
            Path: /postsByAdminUser
            Method: GET
            RestApiId:
              Ref: EAPApi
              
  
  EAPGetPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-get-post
      CodeUri: ./post-crud
      Handler: app.get_post_meta
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        UserPut:
          Type: Api
          Properties:
            Path: /get
            Method: GET
            RestApiId:
              Ref: EAPApi
  
  EAPPutPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-put-post
      CodeUri: ./post-crud
      Handler: app.put_post_meta
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        UserPut:
          Type: Api
          Properties:
            Path: /post
            Method: PUT
            RestApiId:
              Ref: EAPApi
              
  EAPPostShareEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-post-share
      CodeUri: ./share-post
      Handler: app.post_share
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        UserPut:
          Type: Api
          Properties:
            Path: /share
            Method: POST
            RestApiId:
              Ref: EAPApi
              
  EAPPostShareDetailsForUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-post-share-details-for-user
      CodeUri: ./post-share-details-for-user
      Handler: app.post_share_details
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        UserPut:
          Type: Api
          Properties:
            Path: /postShareDetailsForUser
            Method: GET
            RestApiId:
              Ref: EAPApi
              
  EAPPostShareAnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-post-share-analytics
      CodeUri: ./post-share-analytics
      Handler: app.post_share_analytics
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        UserPut:
          Type: Api
          Properties:
            Path: /postShareAnalytics
            Method: GET
            RestApiId:
              Ref: EAPApi
              
  JWTCognitoVerifier:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: jwt-cognito-verifier
      CodeUri: ./jwt-cognito-verify
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          USER_POOL_ID: us-west-2_hlPFRwDKP
          APP_CLIENT_ID: 74lhiqhd1191807a2fsmmrhe6e
            
  EAPApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: eap-web-service
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: eap-openapi.yaml
      
        
    
Outputs:
  ApiUrl:
    Description: "API url of the Prod environment"
    Value: !Sub "https://${EAPApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"