Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        TABLE_NAME: inneedEap
        AWS_REGION_DYNAMODB: us-west-2


Resources:
  EAPCompanyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./eap-company-crud
      Handler: app.crud_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        CompanyGet:
          Type: Api
          Properties:
            Path: /company/{company_id}
            Method: GET
        CompanyPut:
          Type: Api
          Properties:
            Path: /company
            Method: PUT
            RestApiId:
              Ref: EAPApi
            RequestModel:
              Model: CompanyMeta
              Required: true
            
  EAPApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Models:
        CompanyMeta:
          type: object
          required:
            - name
            - domain
            - address
          properties:
            name:
              type: string
            domain:
              type: string
            address:
              type: string
              
      # DefinitionBody:
      #   swagger: 2.0
      #   x-amazon-apigateway-request-validators:
      #     Validate query string parameters and headers:
      #       validateRequestParameters: true
      #       validateRequestBody: true
            
    
Outputs:
  ApiUrl:
    Description: "API url of the Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/resource/"