Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        TABLE_NAME: inneedEap
        AWS_REGION_DYNAMODB: us-west-2


Resources:
  EAPGetCompanyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-get-company
      CodeUri: ./company-crud
      Handler: app.get_company_meta
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        CompanyGet:
          Type: Api
          Properties:
            Path: /company
            Method: GET
                
            RestApiId:
              Ref: EAPApi
              
  
  EAPPutCompanyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-put-company
      CodeUri: ./company-crud
      Handler: app.put_company_meta
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        CompanyPut:
          Type: Api
          Properties:
            Path: /company
            Method: PUT
            RestApiId:
              Ref: EAPApi
              
  EAPGetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-get-user
      CodeUri: ./user-crud
      Handler: app.get_user_meta
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        UserGet:
          Type: Api
          Properties:
            Path: /user
            Method: GET
            RestApiId:
              Ref: EAPApi
              
  
  EAPPutUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-put-user
      CodeUri: ./user-crud
      Handler: app.put_user_meta
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        UserPut:
          Type: Api
          Properties:
            Path: /user
            Method: PUT
            RestApiId:
              Ref: EAPApi
  EAPGetPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-get-post
      CodeUri: ./post-crud
      Handler: app.get_post_meta
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        UserGet:
          Type: Api
          Properties:
            Path: /post
            Method: GET
            RestApiId:
              Ref: EAPApi
              
  
  EAPPutPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-put-post
      CodeUri: ./post-crud
      Handler: app.put_post_meta
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        UserPut:
          Type: Api
          Properties:
            Path: /post
            Method: PUT
            RestApiId:
              Ref: EAPApi
              
  EAPPostShareEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eap-post-share
      CodeUri: ./share-post
      Handler: app.post_share
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
           TableName: inneedEap
      Events:
        UserPut:
          Type: Api
          Properties:
            Path: /share
            Method: POST
            RestApiId:
              Ref: EAPApi
            
  EAPApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: eap-web-service
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: eap-openapi.yml
      
        
    
Outputs:
  ApiUrl:
    Description: "API url of the Prod environment"
    Value: !Sub "https://${EAPApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"